version: 3

dotenv:
  - .env

tasks:
  build:
    cmds:
      - go build -o ./out/gosh
    silent: true

  run:
    cmds:
      - task: build
      - ./out/gosh
    silent: true

  clean:
    cmds:
      - rm -rf ./out
    silent: true
