version: 3

dotenv:
  - .env

tasks:
  build:
    cmds:
      - go build -o ./bin/gosh
    silent: true

  run:
    cmds:
      - go run .
    silent: true

  clean:
    cmds:
      - rm -rf ./bin
      - rm *.log
      - rm *history
    silent: true

  # log:
  #   cmds:
  #     - watch --no-title cat $GOSH_LOG_PATH
  #   silent: true
